services:
  db:
      image: postgres:15-alpine
      container_name: workoutflow_postgres
      ports:
      - "5432:5432"
      environment:
        - POSTGRES_USER=workoutflow
        - POSTGRES_PASSWORD=workoutflow
        - POSTGRES_DB=workoutflow_db